### PR TITLE
A testing version of fcFSM

### PR DESCRIPTION
**Pull request by SJin24**
A testing version of fcFSM is added into CUFSM as a module. Run "batchcufsm5_fcFSM.m" in the "examples" directory to lunch it. For more please see "An introduction to fcFSM.pdf".

### CODE REVIEW

**Comment by SJin24** [comment]
A testing version of fcFSM is added into CUFSM as a module.
1. There is no modification to the current files of CUFSM.
2. Added items: a folder “%CUFSM folder% / analysis / fcFSM” [*] and two files in this folder - “stripmain_fcFSM.m” and “secAnal_fcFSM.m”.
	To avoid modifications to the current file, “stripmain_fcFSM.m” is used instead of “stripmain.m” in this testing. There is no difference between these two files except for 3 short pieces of codes added in “stripmain_fcFSM.m”.
	Most part of the construction process of fcFSM constraint matrices has nothing to do with half-wave length/member length, thus was placed in the “secAnal_fcFSM” function. 
	*Note: “%CUFSM folder%” denotes the install directory of CUFSM, i.e. the directory where the file “cufsm5.m” locates.
3. This testing version of fcFSM runs in batch mode. The FSM models of examples are stored in the folder “%CUFSM folder% / examples / fcFSM_examples”, and the launcher “batchcufsm5_fcFSM.m” locates in the folder “%CUFSM folder% / examples”.
	So, this is the way to test your own example: (1) build the FSM model of your example, the nodes, elements, lengths, and so on, please refer to the illustrating examples; (2) specify the name of your example in “batchcufsm5_fcFSM.m”, then run it.
4. The post-processing of this testing version is independent to the main GUI of CUFSM, but figures of modal decomposition and identification solutions are provided.
5. Further, the modal analysis solutions will also be saved as files and stored in the same directory of the FSM model data: the decomposition solutions “L - fcFSM.mat”, “D - fcFSM.mat”, and “G - fcFSM.mat”, and the general solution with identification results: “general – Idt by fcFSM.mat”.
	These fcFSM solution files can be opened within the main GUI of CUFSM. Especially, in the “Post-Processor” page, open them via “Load another solution” button, they can be compared to other solutions, and be examined in detail, e.g. buckling shapes of the fcFSM solutions.
6. What CUFSM model features are supported in this version of fcFSM?
	(a) End boundary conditions, e.g. S-C, C-G. Supported.
	(b) Springs (all kinds of springs defined in CUFSM). Supported.
	(c) Higher buckling modal analysis. Supported.
	(d) Multiple longitudinal terms. Not supported. Will support this feature in the future versions.
	(e) A longitudinal term not equal to 1 (e.g. m=3). Supported.
	(f) Internal boundary conditions (on the nodes) and user defined constraints (equation constraints). Not supported. There will be a general fcFSM algorithm for arbitrary supporting conditions in the future.
	(g) Quasi-curved cross-sections. Supported
	(h) Curved corners. Supported

**Comment by coldformed** [comment]
Exciting! I will need a little time to play with this one and ask questions. But I expect I should be able to merge it into the main code relatively soon! Since we are not into the GUI yet. Do we have a sort of "standard" section that we are using for comparisons etc.? Regardless, look forward to reading and learning from this code.

**Comment by SJin24** [comment]
Thank you for your time! Professor. There are eleven examples in this PR. Some of them are based on a standard example of a lipped channel 120X80X15X1, while each with an unstandardized setting, such as end boundary conditions, longitudinal term, or curved corners. Solutions of these examples can be compared to the standard example. Another method for comparison is loading the solution files into CUFSM GUI, and reanalyzing it using the current CUFSM solver, then the fcFSM solutions can be compared to standard FSM solutions.
I found creating new examples in batch mode is quite easy. If needed, I can generate other example sections in a short period of time.

**Comment by coldformed** [comment]
Sorry for delays, I know February is a long time back, still working on reviewing this commit. Will have it done before too much longer.

**Comment by SJin24** [comment]
Please take your time, Professor. Too much illustrating examples have been submitted in the previous commit. There are some typos in the previous files and here is a correction to them.

**Comment by coldformed** [comment]
I reviewed the basic function, though not into all the details. I think we should merge this into the regular CUFSM for now, even though we are still working. It is an operable version of cFSM and that is quite good. Once we submit the fcFSM paper I would like to update the notation in SecAnal and stripmain_fcFSM to match that notation if we can. I think it makes sense to have just a separate stripmain for now - we can think about dealign with that merger in the future!

**Comment by SJin24** [comment]
Thanks a lot! I am so glad the force-based modal classification method can have the honor to be introduced into CUFSM.

**Pull request merged**
