### PR TITLE
An optional vectorized version of analysis

### PR DESCRIPTION
**Pull request by SJin24**
1 Except for minor changes to “commandbar.m” and “commandbar_cb.m”, no modification was made to the current files. 
2 Vectorized version of 5 current files, BC_I1_5_vec.m, klocal_vec.m, kglocal_vec.m, trans_vec.m, and stripmain_vec.m, were added. 
3 In the “stripmain_vec.m” file, before solving the eigen value function, a method recommended by MATLAB was conducted to the symmetric matrix Kg: set Kg=(Kg+Kg’)/2, which was found improved the stability of the solving. As the results, the solving can be based on sparse matrixes, and the solving process is simpler and faster. 
4 The option “Vectorizing the computation” can be switched on/off through a menu item. 
5 If it is switched on, the 5 vectorized files will be used, otherwise the current version of files will be used. 
6 Analysis waitbar was temporarily resumed, because the computation could take some time when considering multiple longitudinal terms. 
7 For an example considering 20 longitudinal terms (1 ~ 20), the vectorized version of computation is about 15 ~ 20 times faster than the current version (by computers assembled with intel CPUs). 
8 For signature curve problems (only one longitudinal term), there is no obvious calculating speed difference between the two versions (waitbar takes most time).

### CODE REVIEW

**Comment by coldformed** [comment]
I am reviewing! This one gives me various thoughts so it may take me a day or two before I get back to you on this one. Keep trying to think if it is better to have the codes in the same m file.. or to have a new family of files as you have done here. I will dig in - exciting so see all these improvements come to CUFSM.

**Comment by SJin24** [comment]
Thank you! Please take your time. I will think about the question which way to organize these files should be better.

**Comment by coldformed** [comment]
It seems like a shame to have to have 2 version of klocal for example. But inside klocal we need to have a switch between normal version and vectorized version. Which means that we need a new variable to pass to klocal. Which means existing calls to klocal won't work (say from stripmain) unless we define this new version. But, we could use the "varargin" for klocal and even for stripmain... If no last argument is passed we assume you use the normal code, otherwise we pass a flag that says use the vectorized version. In that case, all existing calls still work, but all new calls that pass in a boolean about the vectorized version or not should still work. Does this idea make sense? If yes, do you want to try it out..

The main thing I worry about is having two version of stripmain.m, the other functions, if we want to keep them, could all go in ../analysis/vectorized/files... that would be a good solution as well for keeping everything clear.

Give this some thought, let me know what you think, then we can implement. :-)

**Comment by SJin24** [comment]
Yes, "varargin" is a good idea, making the codes neat and elegant. I will think about it and try updating in this way. My connection to GitHub is unstable, God knows how many times should have I tried before getting this posted~~~

**Comment by SJin24** [comment]
I tried it in this way and everything looks better:
1 The “varargin” is used in the “stripmain” function and the updates in the “stripmain_vec” are merged in “stripmain”. Calls to stripmain remain the same as before if vectorizing is not needed, and if an extra bollean variable “true” is passed, it will run in vectorized way.
2 stripmain_vec.m is not needed and deleted, the other four vectorized files are placed in the “.../analysis/vectorized/” directory. I think maybe they can be merged to the original files later, after having been widely tested.

**Comment by coldformed** [comment]
I did not find the time I was hoping for today to play with this more, so it will likely be the end of the week. I am supportive of the overall idea here! Will give more feedback soon.

**Comment by coldformed** [comment]
Under Elastic Buckling in the GUI menu, let's have "vectorized" and "normal" and one of the two check marked, Then on the commander can we use a radio button maybe tween "vectorized" and "normal" right of the number 2 and the little matrix button or similar?

**Comment by SJin24** [comment]
The menu items and the commandbar toggle tool are added.

**Comment by coldformed** [comment]
I made some small tweaks you should pull those down to your version. Critical was to add the path to the subdirectory with vectorized in it.

Is vargin implemented in stripmain right now, or is it require that ifVec be passed to the function. I did not check this thoroughly, but my looking at the code is that ifVec is required to be passed in. I ask because I was thinking about batchcufsm and other scripts and whether they will need to be modified. I think if we implement this way, they do need to be modified. 

The checkmark for vector v normal in the menu structure working well. The button in the toolbar to show if vectorized or normal not working on my Mac. The 'State' 'on', 'State' 'off' really does not look different on my machine. Maybe we need to images one dark and one in light grey or something to make that work manually.

Also one more thing, I ended up with dead waitbar's again as I was debugging. That waiter in stripmain seems to cause issues - we may need to revisit the code I commented out and carefully go through how we implement waitbar so that we don't end up generating all those dead windows that have to be killed off...

**Comment by SJin24** [comment]
The stripmain function has 11  input arguments.  If it is called with no more than 10 input arguments, the last one (ifVec) will be set to 0 automatically.  Then if called with no more than 9 arguments, the last but one (neigs) will be set to 20. So I think this function can be used the same way as before.

I found with few modifications we can close the waitbar by pressing the "Cancel" and close (x) buttons of that dialog, no matter during the calculation or stopped due to an error. Will soon pull an update for you to review.

**Comment by coldformed** [comment]
Sounds great, I will look for the updates this week. Been working on the fcFSM paper with Sandor, also a lot of fun, and more motivation to work on getting fcFSM into CUFSM, at least the algorithms to start..

**Comment by coldformed** [comment]
image

Button works, but pretty abstract, and all other items on toolbar that you click create actions. 

Let's put this toggle closer to the "analysis" button, and just have it say in tiny text stacked
**vec**
norm
or
vec
**norm**

or something similar.. the current images are fun, but don't mean anything to me..

**Comment by SJin24** [comment]
Thanks a lot! Professor. I will do it, and will soon start working on fcFSM. That should also be very interesting!

**Comment by coldformed** [comment]
Looks good. Let's make the default "normal" and the user needs to choose "vectorized". Then I will merge this back into the main branch and we can get going on the next piece.

**Comment by coldformed** [comment]
After we get this merged back in make sure to fork back off the main, as we have made other small changes too.

**Comment by SJin24** [comment]
Currently I relied on the experience that a variable is automatically set to 0 at the initialization, so that the first time when it is declared the state will be set to be “normal” by default automatically, but that might not be the thing in Mac OS.
So I will declare a global bool variable as the sign “vectorized / normal” and set it to be false (indicating “normal”) at the startup of the program, i.e. cufsm5.m. As before, this bool variable can be changed by users through the corresponding menu items and command bar toggle tool.
Is that right?

**Comment by coldformed** [comment]
Your system should be fine, let me check it all, hopefully today.

**Pull request merged**
