### PR TITLE
A new 3D shape plotting style

### PR DESCRIPTION
**Pull request by SJin24**
A new 3D mode shape plotting style, namely "curved lines" is added, which is more in line with the spirit of FSM, and helps users better understanding how the 2D plotting is cut from the member.

### CODE REVIEW

**Comment by coldformed** [comment]
Let's set the default so it is the same isometric as the others, the user can rotate it to 2D to see the 1-1 explanation, but just the ability to see the red 2D deformed shape at the appropriate part of the longitudinal section is a real breakthrough for visualization on this one.

**Comment by coldformed** [comment]
After default is set to iso, I will merge it in, looks great - another improvement to CUFSM!

**Comment by SJin24** [comment]
Thank you! Professor. The default settings of the “curved lines” style is now the same as other 3D styles, is that right?

**Comment by coldformed** [comment]
Excellent!

**Pull request merged**
